### ISSUE TITLE
Data type

### ISSUE THREAD

**Issue by rguo123** [neurodata/ingest_large_vol#14]
Ingest large vol won't find the correct data type. Currently have to manually specify the data type in the ingest_large_vol.py script.

**Comment by falkben** [comment]
This is intended behavior for now to avoid ingesting the wrong data.  On the roadmap is a command line flag to "discover properties of images" which will automatically find the datatype, image size, # of images in a dataset and use that for ingest.

Pull requests welcome if you are inclined to work on this feature.
